import { useState } from "react";
import { Bot, BrainCircuit, CircleDollarSign, Crosshair, Gauge, ShieldCheck, Sparkles, TrendingUp, WalletCards } from "lucide-react";
import { AIActivityFeed, BubbleMap, DemoBadge, MetricCard, PageHeader, Panel, PnlChart, PositionTable, RiskPanel, SmartMoneyBubble, StrategyPanel, TokenTable, TradeTable, WalletPanel } from "./HunterUI";
import { portfolio, wallets } from "@/lib/mock-data";

const iconMap = [CircleDollarSign, TrendingUp, Crosshair, Gauge, BrainCircuit, Sparkles];
export function OverviewPage() { return <div className="page"><PageHeader title="HUNTER 2X" subtitle="AI-powered Solana opportunity detection" action={<div className="hidden text-right sm:block"><span className="eyebrow">OPERATING MODE</span><p className="mt-1 text-sm font-semibold text-warning">PAPER MODE</p></div>}/><div className="metrics-grid">{portfolio.map((m,i)=><MetricCard key={m.label} {...m} icon={iconMap[i]}/>)}</div><div className="mt-4"><div className="mb-3 flex items-center justify-between"><div><h2 className="font-display text-lg font-semibold">Opportunity Map</h2><p className="text-xs text-muted-foreground">Token relationships and signal density</p></div><DemoBadge/></div><BubbleMap/></div></div>; }
export function MapPage() { return <div className="page"><PageHeader title="HUNTER MAP" subtitle="Explore token clusters, wallets, liquidity and Smart Money overlap"/><BubbleMap expanded/></div>; }
export function ScannerPage() { return <div className="page"><PageHeader title="TOKEN SCANNER" subtitle="Ranked Solana opportunities using simulated market intelligence"/><TokenTable/></div>; }
export function SmartMoneyPage() { const [selected,setSelected]=useState(0); const w=wallets[selected] ?? wallets[0]; if(!w)return null; return <div className="page"><PageHeader title="SMART MONEY" subtitle="Tracked wallet behavior and capital flow intelligence"/><div className="grid gap-4 xl:grid-cols-[1fr_340px]"><Panel title="WALLET NETWORK"><div className="wallet-map">{wallets.map((x,i)=><button key={x.id} onClick={()=>setSelected(i)}><SmartMoneyBubble score={x.score} label={x.id}/></button>)}</div></Panel><Panel title="WALLET INTELLIGENCE"><p className="font-mono text-xs text-muted-foreground">{w.address}</p><div className="mt-5 data-grid"><span>Wallet score<b className="text-primary">{w.score}</b></span><span>Win rate<b>{w.winRate}</b></span><span>P&L<b className="text-positive">{w.pnl}</b></span><span>Positions<b>{w.positions}</b></span><span>Recent buys<b>{w.buys}</b></span><span>Recent sells<b>{w.sells}</b></span></div><p className="eyebrow mt-5">TOKENS TRADED</p><div className="mt-2 flex gap-2">{w.tokens.map(t=><span className="badge-demo" key={t}>${t}</span>)}</div></Panel></div></div>; }
export function PositionsPage() { return <div className="page"><PageHeader title="OPEN POSITIONS" subtitle="Paper positions and simulated performance tracking"/><div className="mb-4 grid gap-3 sm:grid-cols-3"><MetricCard label="Position value" value="$47.00" trend="4 positions"/><MetricCard label="Unrealized P&L" value="+$17.41" trend="+37.0%" tone="positive"/><MetricCard label="Average score" value="86.2" trend="High conviction" tone="ai"/></div><PositionTable/><div className="mt-4"><PnlChart/></div></div>; }
export function HistoryPage() { const stats=[["Win rate","61.4%"],["Average winner","+$8.72"],["Average loser","-$3.14"],["Profit factor","2.31"],["Total P&L","+$68.40"],["Maximum drawdown","-12.8%"]]; return <div className="page"><PageHeader title="TRADE HISTORY" subtitle="Completed paper trades and strategy outcomes"/><div className="metrics-grid mb-4">{stats.map(([label,value])=><MetricCard key={label} label={label} value={value} tone={value.startsWith("+")||label==="Win rate"?"positive":"neutral"}/>)}</div><TradeTable/></div>; }
export function StrategiesPage() { return <div className="page"><PageHeader title="STRATEGY BUILDER" subtitle="Configure the HUNTER 2X paper strategy"/><StrategyPanel/></div>; }
export function RiskPage() { return <div className="page"><PageHeader title="RISK MANAGEMENT" subtitle="Set simulated trading limits and monitor system health"/><RiskPanel/></div>; }
export function WalletPage() { return <div className="page"><PageHeader title="WALLET" subtitle="Future wallet controls — no connection or signing is enabled"/><div className="grid gap-4 2xl:grid-cols-2"><WalletPanel/><WalletPanel vault/></div></div>; }
export function AIAgentPage() { return <div className="page"><PageHeader title="HUNTER AI" subtitle="Autonomous intelligence activity preview" action={<span className="top-status"><span className="status-dot status-positive"/> READY</span>}/><div className="grid gap-4 md:grid-cols-3"><MetricCard label="AI MODEL" value="Connected later" trend="No API configured" icon={Bot}/><MetricCard label="GMGN AGENT" value="Not connected" trend="Future integration" icon={BrainCircuit}/><MetricCard label="MARKET INTELLIGENCE" value="Waiting for data" trend="Demo stream active" icon={Sparkles}/></div><div className="mt-4"><AIActivityFeed/></div></div>; }
export { SettingsSections } from "./HunterUI";