import { Link, useRouterState } from "@tanstack/react-router";
import { useMemo, useRef, useState, type ReactNode, type WheelEvent, type MouseEvent as ReactMouseEvent } from "react";
import { Activity, Bot, BrainCircuit, CandlestickChart, ChevronLeft, ChevronRight, CircleDollarSign, Crosshair, Filter, Gauge, History, Menu, Minus, Network, Plus, Radar, RotateCcw, Search, Settings, ShieldCheck, SlidersHorizontal, Sparkles, Target, UserRound, WalletCards, X } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip as ChartTooltip, XAxis, YAxis } from "recharts";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Slider } from "@/components/ui/slider";
import { Switch } from "@/components/ui/switch";
import { Drawer, DrawerContent, DrawerHeader, DrawerTitle, DrawerTrigger } from "@/components/ui/drawer";
import { cn } from "@/lib/utils";
import { aiEvents, pnlSeries, positions, relationships, signals, tokens, trades, wallets, type Token } from "@/lib/mock-data";

const nav = [
  ["/", "Overview", Radar], ["/hunter-map", "Hunter Map", Network], ["/token-scanner", "Token Scanner", Search],
  ["/smart-money", "Smart Money", BrainCircuit], ["/positions", "Positions", CandlestickChart], ["/trade-history", "Trade History", History],
  ["/strategies", "Strategies", SlidersHorizontal], ["/risk", "Risk", ShieldCheck], ["/wallet", "Wallet", WalletCards],
  ["/ai-agent", "AI Agent", Bot], ["/settings", "Settings", Settings],
] as const;

export function DemoBadge() { return <span className="badge-demo">DEMO DATA</span>; }
export function Dot({ tone = "positive" }: { tone?: string }) { return <span className={cn("status-dot", `status-${tone}`)} />; }

export function TopBar({ onMenu }: { onMenu: () => void }) {
  return <header className="topbar">
    <div className="flex min-w-0 items-center gap-3"><Button size="icon" variant="ghost" className="lg:hidden" onClick={onMenu} aria-label="Open navigation"><Menu /></Button><div className="brand-mark"><Crosshair /></div><strong className="font-display text-lg tracking-normal">HUNTER <span className="text-primary">2X</span></strong></div>
    <div className="hidden items-center gap-5 md:flex"><span className="top-status"><Dot tone="warning" /> PAPER MODE</span><span className="top-status text-muted-foreground"><WalletCards /> NOT CONNECTED</span><span className="top-status"><Dot /> ONLINE</span></div>
    <Button size="icon" variant="ghost" aria-label="User settings"><UserRound /></Button>
  </header>;
}

export function Sidebar({ mobile = false, close }: { mobile?: boolean; close?: () => void }) {
  const path = useRouterState({ select: s => s.location.pathname });
  return <aside className={cn("sidebar", mobile && "h-full w-full border-r-0")}><nav className="flex-1 space-y-1 p-3">{nav.map(([to, label, Icon]) => <Link key={to} to={to} onClick={close} className={cn("nav-item", path === to && "nav-active")}><Icon /><span>{label}</span>{path === to && <span className="ml-auto h-1 w-1 rounded-full bg-primary" />}</Link>)}</nav><div className="border-t border-border p-4"><p className="eyebrow">BOT STATUS</p><div className="my-3 flex items-center justify-between text-xs"><span className="flex items-center gap-2 font-semibold"><Dot tone="warning" />PAPER MODE</span><DemoBadge /></div><Button className="w-full" onClick={() => undefined}><Target /> START HUNTER</Button></div></aside>;
}

export function SignalFeed({ compact = false }: { compact?: boolean }) { return <div className="space-y-2">{signals.slice(0, compact ? 3 : 5).map((s, i) => <article className="signal-item animate-fade-in" style={{ animationDelay: `${i * 80}ms` }} key={s.type + s.token}><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-[10px] font-bold text-muted-foreground"><Dot tone={s.tone} />{s.type}</span><span className="text-[10px] text-muted-foreground">{s.time}</span></div><div className="mt-2 grid grid-cols-[1fr_auto] gap-3"><div><strong>{s.token}</strong><p className="mt-1 text-xs text-muted-foreground">{s.detail}</p></div><HunterScore score={s.score} small /></div></article>)}</div>; }

export function StatusBar() { return <footer className="statusbar">{[["NETWORK","SOLANA","ai"],["DATA","DEMO","warning"],["BOT","PAPER","warning"],["GMGN","NOT CONNECTED","muted"],["WALLET","NOT CONNECTED","muted"],["SYSTEM","ONLINE","positive"]].map(([a,b,t]) => <span key={a}><Dot tone={t} /><small>{a}</small><b>{b}</b></span>)}</footer>; }

export function AppShell({ children }: { children: ReactNode }) {
  const [menu, setMenu] = useState(false); const [intel, setIntel] = useState(false);
  return <div className="min-h-screen bg-background text-foreground"><TopBar onMenu={() => setMenu(true)} /><div className="app-grid"><div className="hidden lg:block"><Sidebar /></div><main className="min-w-0 overflow-x-hidden pb-12">{children}</main><aside className="intel-panel hidden xl:block"><div className="flex items-center justify-between border-b border-border p-4"><div><p className="eyebrow">AI INTELLIGENCE</p><p className="mt-1 text-xs text-muted-foreground">Signal stream · simulated</p></div><Sparkles className="text-primary" /></div><div className="p-3"><SignalFeed /></div></aside></div><StatusBar />
    <Drawer open={menu} onOpenChange={setMenu}><DrawerContent className="h-[86vh]"><DrawerHeader><DrawerTitle>Navigation</DrawerTitle></DrawerHeader><Sidebar mobile close={() => setMenu(false)} /></DrawerContent></Drawer>
    <Button size="sm" className="fixed bottom-10 right-3 z-40 xl:hidden" onClick={() => setIntel(true)}><BrainCircuit /> Intelligence</Button>
    <Drawer open={intel} onOpenChange={setIntel}><DrawerContent><DrawerHeader><DrawerTitle>AI Intelligence</DrawerTitle></DrawerHeader><div className="max-h-[65vh] overflow-y-auto p-4"><SignalFeed /></div></DrawerContent></Drawer>
  </div>;
}

export function PageHeader({ title, subtitle, action }: { title: string; subtitle: string; action?: ReactNode }) { return <div className="page-header"><div className="min-w-0"><div className="mb-2 flex items-center gap-2"><DemoBadge /><span className="top-status"><Dot /> SYSTEM ONLINE</span></div><h1>{title}</h1><p>{subtitle}</p></div>{action}</div>; }
export function Panel({ children, className, title, aside }: { children: ReactNode; className?: string; title?: string; aside?: ReactNode }) { return <section className={cn("panel", className)}>{title && <div className="panel-title"><h2>{title}</h2>{aside}</div>}{children}</section>; }
export function MetricCard({ label, value, trend, tone = "neutral", icon: Icon = Activity }: { label: string; value: string; trend?: string; tone?: string; icon?: typeof Activity }) { return <article className="metric-card"><div className="flex items-center justify-between"><span className="eyebrow">{label}</span><Icon className="h-4 w-4 text-muted-foreground" /></div><strong className={cn("mt-4 block text-2xl font-semibold", tone === "positive" && "text-positive", tone === "ai" && "text-primary")}>{value}</strong>{trend && <span className={cn("mt-1 block text-xs", tone === "positive" ? "text-positive" : "text-muted-foreground")}>{trend}</span>}</article>; }
export function HunterScore({ score, small = false }: { score: number; small?: boolean }) { const color = score >= 85 ? "text-positive" : score >= 70 ? "text-warning" : "text-negative"; return <div className={cn("score-ring", small ? "h-11 w-11" : "h-32 w-32")} style={{ "--score": `${score * 3.6}deg` } as React.CSSProperties}><div className="score-inner"><strong className={cn(color, small ? "text-xs" : "text-3xl")}>{score}</strong>{!small && <small>/100</small>}</div></div>; }

type SizeMetric = "marketCap" | "liquidity" | "volume" | "smartMoney";
const metricLabels: Record<SizeMetric, string> = { marketCap: "Market Cap", liquidity: "Liquidity", volume: "Volume", smartMoney: "Smart Money" };
export function BubbleMap({ expanded = false }: { expanded?: boolean }) {
  const [sizeBy, setSizeBy] = useState<SizeMetric>("marketCap"); const [selected, setSelected] = useState<Token | null>(null); const [hovered, setHovered] = useState<Token | null>(null); const [scale, setScale] = useState(1); const [offset, setOffset] = useState({ x: 0, y: 0 }); const [drag, setDrag] = useState<{x:number;y:number;ox:number;oy:number}|null>(null); const [filter, setFilter] = useState("ALL"); const svgRef = useRef<SVGSVGElement>(null);
  const visible = useMemo(() => tokens.filter(t => filter === "ALL" || filter === "SMART MONEY" && t.smartMoney > 82 || filter === "MOMENTUM" && t.change5m > 20 || filter === "HIGH LIQUIDITY" && t.liquidity > 180000 || filter === "HIGH VOLUME" && t.volume > 400000 || filter === "AI SIGNAL" && t.hunterScore > 85 || filter === "NEW LAUNCHES" && t.age < 12 || filter === "WATCHLIST" && ["ABC","WIF","NOVA","DOG"].includes(t.symbol)), [filter]);
  const radius = (t: Token) => { const vals = visible.map(x => x[sizeBy]); const max = Math.max(...vals, 1); return 18 + Math.sqrt(Number(t[sizeBy]) / max) * (expanded ? 35 : 28); };
  const connections = selected ? relationships.filter(r => r.from === selected.symbol || r.to === selected.symbol) : relationships;
  const onWheel = (e: WheelEvent<SVGSVGElement>) => { e.preventDefault(); setScale(v => Math.max(.65, Math.min(2.2, v + (e.deltaY < 0 ? .1 : -.1)))); };
  return <div className={cn("map-shell", expanded ? "h-[calc(100vh-230px)] min-h-[620px]" : "h-[580px]")}>
    <div className="map-toolbar"><div className="segmented"><span>SIZE BY</span>{(Object.keys(metricLabels) as SizeMetric[]).map(k => <button key={k} className={sizeBy === k ? "active" : ""} onClick={() => setSizeBy(k)}>{metricLabels[k]}</button>)}</div><div className="flex gap-1"><Button size="icon" variant="outline" onClick={() => setScale(v => Math.min(2.2, v + .15))} aria-label="Zoom in"><Plus /></Button><Button size="icon" variant="outline" onClick={() => setScale(v => Math.max(.65, v - .15))} aria-label="Zoom out"><Minus /></Button><Button size="sm" variant="outline" onClick={() => { setScale(1); setOffset({x:0,y:0}); }}><RotateCcw /> Reset</Button></div></div>
    <div className="filter-strip">{["ALL","NEW LAUNCHES","SMART MONEY","MOMENTUM","HIGH LIQUIDITY","HIGH VOLUME","AI SIGNAL","WATCHLIST"].map(f => <button key={f} onClick={() => setFilter(f)} className={filter === f ? "active" : ""}>{f}</button>)}</div>
    <svg ref={svgRef} viewBox="0 0 930 540" className="h-full w-full cursor-grab active:cursor-grabbing" onWheel={onWheel} onMouseDown={e => setDrag({x:e.clientX,y:e.clientY,ox:offset.x,oy:offset.y})} onMouseMove={(e:ReactMouseEvent<SVGSVGElement>) => drag && setOffset({x:drag.ox+(e.clientX-drag.x)/scale,y:drag.oy+(e.clientY-drag.y)/scale})} onMouseUp={() => setDrag(null)} onMouseLeave={() => {setDrag(null);setHovered(null)}}>
      <defs><radialGradient id="bubble"><stop offset="0" stopColor="var(--primary-soft)"/><stop offset="1" stopColor="var(--surface-deep)"/></radialGradient><filter id="glow"><feGaussianBlur stdDeviation="4" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>
      <g transform={`translate(${offset.x} ${offset.y}) scale(${scale})`} className="origin-center transition-transform duration-100">{connections.map((r, i) => { const a=tokens.find(t=>t.symbol===r.from), b=tokens.find(t=>t.symbol===r.to); if(!a||!b||!visible.includes(a)||!visible.includes(b)) return null; return <line key={i} x1={a.x} y1={a.y} x2={b.x} y2={b.y} className={`link link-${r.type.toLowerCase().replace(" ", "-")}`} />; })}{visible.map(t => <TokenBubble key={t.symbol} token={t} radius={radius(t)} selected={selected?.symbol === t.symbol} related={!!selected && connections.some(r=>r.from===t.symbol||r.to===t.symbol)} onHover={setHovered} onSelect={setSelected} />)}</g>
    </svg>
    {hovered && <TokenTooltip token={hovered} />}
    <div className="map-legend"><DemoBadge /><span><i className="bg-positive"/>Bullish</span><span><i className="bg-negative"/>Bearish</span><span><i className="bg-primary"/>AI signal</span></div>
    {selected && <TokenDetailPanel token={selected} onClose={() => setSelected(null)} />}
  </div>;
}

export function TokenBubble({ token, radius, selected, related, onHover, onSelect }: { token: Token; radius: number; selected: boolean; related: boolean; onHover:(t:Token|null)=>void; onSelect:(t:Token)=>void }) { const tone = token.change5m >= 0 ? "positive" : "negative"; return <g className={cn("token-node", selected && "selected", related && "related")} transform={`translate(${token.x} ${token.y})`} onMouseEnter={() => onHover(token)} onMouseLeave={() => onHover(null)} onClick={e => {e.stopPropagation();onSelect(token)}} role="button" tabIndex={0}><circle r={radius} fill="url(#bubble)" className={`bubble-stroke-${tone}`} /><circle r={radius-4} className="bubble-core"/><text textAnchor="middle" y="-2" className="bubble-label">${token.symbol}</text><text textAnchor="middle" y="13" className={`bubble-change ${tone}`}>{token.change5m > 0 ? "+" : ""}{token.change5m}%</text>{token.smartMoney > 85 && <circle cx={radius*.7} cy={-radius*.7} r="5" className="fill-warning node-beacon"/>}</g>; }
export function SmartMoneyBubble({ score, label }: { score:number; label:string }) { return <div className="wallet-bubble" style={{"--wallet-size": `${80 + (score-70)*2}px`} as React.CSSProperties}><BrainCircuit/><strong>{label}</strong><span>{score} SCORE</span></div>; }
export function TokenTooltip({ token }: { token:Token }) { return <div className="token-tooltip"><div className="flex justify-between"><strong>${token.symbol}</strong><span className={token.change5m>=0?"text-positive":"text-negative"}>{token.change5m>0?"+":""}{token.change5m}%</span></div><dl><dt>Price</dt><dd>{token.price}</dd><dt>Market cap</dt><dd>{money(token.marketCap)}</dd><dt>Liquidity</dt><dd>{money(token.liquidity)}</dd><dt>Volume</dt><dd>{money(token.volume)}</dd><dt>Smart Money</dt><dd>{token.smartMoney}</dd><dt>Hunter score</dt><dd>{token.hunterScore}</dd></dl></div>; }
export function TokenDetailPanel({ token, onClose }: { token:Token; onClose:()=>void }) { return <aside className="token-detail"><div className="flex items-start justify-between"><div><p className="eyebrow">TOKEN INTELLIGENCE</p><h2 className="mt-1 text-xl font-semibold">${token.symbol}</h2><p className="font-mono text-[10px] text-muted-foreground">{token.address}</p></div><Button size="icon" variant="ghost" onClick={onClose} aria-label="Close details"><X /></Button></div><div className="my-5 flex items-center gap-5"><HunterScore score={token.hunterScore}/><div><p className="eyebrow">SIGNAL</p><strong className="text-positive">{token.signal === "BUY" ? "HIGH CONVICTION" : token.signal}</strong><p className="mt-2 text-xs text-muted-foreground">Simulated signal</p></div></div><div className="data-grid"><span>Price<b>{token.price}</b></span><span>Market Cap<b>{money(token.marketCap)}</b></span><span>Liquidity<b>{money(token.liquidity)}</b></span><span>Volume<b>{money(token.volume)}</b></span><span>Holders<b>{token.holders.toLocaleString()}</b></span><span>Smart Money<b>{token.smartMoney}</b></span></div><MiniChart values={[18,24,21,34,29,41,38,55,61,58,72]} /><div className="mt-4 grid grid-cols-3 gap-2 text-center text-[10px]"><span className="mini-stat">5M<b>{token.change5m}%</b></span><span className="mini-stat">15M<b>+42%</b></span><span className="mini-stat">1H<b>{token.change1h}%</b></span></div><div className="mt-4 border-t border-border pt-4"><p className="eyebrow mb-2">AI ANALYSIS</p><p className="text-xs leading-5 text-muted-foreground">Strong wallet accumulation with improving liquidity depth. Momentum remains elevated; holder concentration is within the simulated risk threshold.</p></div></aside>; }

export function MiniChart({ values = pnlSeries }: { values?: number[] }) { const data=values.map((v,i)=>({i,v})); return <div className="mt-4 h-28"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data}><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--positive)" stopOpacity={.35}/><stop offset="1" stopColor="var(--positive)" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="var(--border)" vertical={false}/><Area type="monotone" dataKey="v" stroke="var(--positive)" fill="url(#area)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div>; }
export const money=(n:number)=>n>=1_000_000?`$${(n/1_000_000).toFixed(2)}M`:`$${Math.round(n/1000)}K`;

export function TokenTable() { const [q,setQ]=useState(""); const [sort,setSort]=useState<keyof Token>("hunterScore"); const [page,setPage]=useState(0); const rows=useMemo(()=>tokens.filter(t=>(t.symbol+t.name).toLowerCase().includes(q.toLowerCase())).sort((a,b)=>Number(b[sort])-Number(a[sort])).slice(page*10,page*10+10),[q,sort,page]); const cols:[keyof Token,string][]=[["symbol","Token"],["price","Price"],["marketCap","Market Cap"],["liquidity","Liquidity"],["change5m","5M"],["change1h","1H"],["volume","Volume"],["smartMoney","Smart Money"],["holders","Holders"],["hunterScore","Hunter Score"],["signal","Signal"]]; return <Panel><div className="table-tools"><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground"/><Input value={q} onChange={e=>{setQ(e.target.value);setPage(0)}} placeholder="Search token or symbol" className="pl-9"/></div><Button variant="outline"><Filter/> Filters</Button></div><div className="overflow-x-auto"><table className="data-table"><thead><tr>{cols.map(([k,l])=><th key={k}><button onClick={()=>setSort(k)}>{l}{sort===k&&<span className="text-primary"> ↓</span>}</button></th>)}</tr></thead><tbody>{rows.map(t=><tr key={t.symbol}>{cols.map(([k])=><td key={k} className={k.includes("change")?(Number(t[k])>=0?"text-positive":"text-negative"):k==="signal"?"font-semibold text-primary":""}>{k==="symbol"?<strong>${t.symbol}</strong>:k==="marketCap"||k==="liquidity"||k==="volume"?money(Number(t[k])):k==="change5m"||k==="change1h"?`${Number(t[k])>0?"+":""}${t[k]}%`:String(t[k])}</td>)}</tr>)}</tbody></table></div><div className="flex items-center justify-between border-t border-border p-3 text-xs text-muted-foreground"><span>Showing {page*10+1}–{Math.min(page*10+10,tokens.length)} of {tokens.length}</span><div className="flex gap-1"><Button size="icon" variant="outline" disabled={page===0} onClick={()=>setPage(p=>p-1)}><ChevronLeft/></Button><Button size="icon" variant="outline" disabled={(page+1)*10>=tokens.length} onClick={()=>setPage(p=>p+1)}><ChevronRight/></Button></div></div></Panel>; }

export function PositionTable() { return <Panel><div className="overflow-x-auto"><table className="data-table"><thead><tr>{["Token","Entry","Current","Position Size","P&L","P&L %","Hunter Score","Strategy","TP","SL","Status"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{positions.map(p=><tr key={p.token}>{Object.entries(p).map(([k,v])=><td key={k} className={k.startsWith("pnl")?(String(v).startsWith("+")?"text-positive":"text-negative"):k==="status"?"text-primary":""}>{v}</td>)}</tr>)}</tbody></table></div></Panel>; }

export function StrategyPanel() { const [values,setValues]=useState({hunter:80,liquidity:50000,smart:75,size:10,max:5,tp:2,sl:20}); const [toggles,setToggles]=useState({trailing:true,partial:true,newLaunches:false,smart:true,momentum:true}); return <Panel title="HUNTER 2X" aside={<span className="top-status"><Dot/> ACTIVE DRAFT</span>}><div className="form-grid">{[["Hunter Score","hunter",0,100,""],["Minimum Liquidity","liquidity",10000,250000,"$"],["Smart Money Score","smart",0,100,""],["Position Size","size",5,100,"$"],["Maximum Positions","max",1,12,""],["Take Profit","tp",1,5,"x"],["Stop Loss","sl",5,50,"%"]].map(([label,key,min,max,suffix])=><label className="control-row" key={String(key)}><span><b>{label}</b><small>{suffix}{values[key as keyof typeof values]}{suffix==="$"&&key==="liquidity"?"":suffix && suffix!=="$"?suffix:""}</small></span><Slider min={Number(min)} max={Number(max)} step={key==="tp"?.1:1} value={[values[key as keyof typeof values]]} onValueChange={v=>setValues(x=>({...x,[key]:v[0]}))}/></label>)}</div><div className="mt-5 grid gap-2 md:grid-cols-2">{Object.entries(toggles).map(([key,val])=><label className="toggle-row" key={key}><span>{({trailing:"Trailing Stop",partial:"Partial TP",newLaunches:"Allow New Launches",smart:"Allow Smart Money Signals",momentum:"Allow Momentum Signals"} as Record<string,string>)[key]}</span><Switch checked={val} onCheckedChange={v=>setToggles(x=>({...x,[key]:v}))}/></label>)}</div></Panel>; }
export function RiskPanel() { const [risk,setRisk]=useState({daily:50,trade:10,positions:5,exposure:50,slippage:5,losses:5}); return <div className="grid gap-4 xl:grid-cols-[1fr_340px]"><Panel title="Risk Limits"><div className="form-grid">{Object.entries(risk).map(([key,val])=><label className="control-row" key={key}><span><b>{({daily:"Maximum Daily Loss",trade:"Maximum Trade Loss",positions:"Maximum Positions",exposure:"Maximum Exposure",slippage:"Maximum Slippage",losses:"Consecutive Loss Limit"} as Record<string,string>)[key]}</b><small>{["daily","trade","exposure"].includes(key)?"$":""}{val}{key==="slippage"?"%":""}</small></span><Slider value={[val]} max={key==="slippage"?15:key==="positions"||key==="losses"?12:100} min={1} onValueChange={v=>setRisk(x=>({...x,[key]:v[0]}))}/></label>)}</div></Panel><div className="space-y-4"><Panel title="DAILY RISK"><div className="mt-5 flex justify-between"><strong className="text-2xl">$18.42</strong><span className="text-muted-foreground">/ ${risk.daily}</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-warning transition-all" style={{width:`${Math.min(100,18.42/risk.daily*100)}%`}}/></div></Panel><Panel title="BOT HEALTH"><div className="flex items-center gap-4 py-4"><div className="grid h-14 w-14 place-items-center rounded-full bg-positive/10 text-positive"><ShieldCheck/></div><div><strong className="text-xl text-positive">SAFE</strong><p className="text-xs text-muted-foreground">All limits within range</p></div></div></Panel></div></div>; }
export function WalletPanel({ vault=false }: {vault?:boolean}) { return <Panel title={vault?"VAULT WALLET":"TRADING WALLET"} aside={<span className="top-status text-muted-foreground"><Dot tone="muted"/> NOT CONNECTED</span>}><div className="grid min-h-64 place-items-center text-center"><div><div className="mx-auto grid h-16 w-16 place-items-center rounded-full border border-border bg-secondary"><WalletCards className="text-muted-foreground"/></div><h3 className="mt-4 font-semibold">No wallet connected</h3><p className="mx-auto mt-2 max-w-sm text-sm text-muted-foreground">Wallet connectivity will be added in a later phase. This control is a visual preview only.</p><Button className="mt-5" onClick={()=>undefined}>Connect{vault?"":" Wallet"}</Button></div></div>{!vault&&<div className="data-grid"><span>Balance<b>—</b></span><span>Available<b>—</b></span><span>In Positions<b>—</b></span><span>P&L<b>—</b></span></div>}</Panel>; }
export function AIActivityFeed() { return <Panel title="ACTIVITY STREAM" aside={<DemoBadge/>}><div className="terminal-feed">{aiEvents.map((e,i)=><div key={e} className="animate-fade-in" style={{animationDelay:`${i*120}ms`}}><span>{`16:${42-i}:0${i}`}</span><Dot tone={i%3===0?"positive":"ai"}/><p>{e}</p></div>)}</div></Panel>; }

export function TradeTable() { return <Panel><div className="overflow-x-auto"><table className="data-table"><thead><tr>{["Time","Token","Side","Entry","Exit","Size","P&L","Strategy","Exit reason"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{trades.map((t,i)=><tr key={i}>{Object.entries(t).map(([k,v])=><td key={k} className={k==="pnl"?(String(v).startsWith("+")?"text-positive":"text-negative"):k==="side"?(v==="BUY"?"text-positive":"text-negative"):""}>{v}</td>)}</tr>)}</tbody></table></div></Panel>; }
export function PnlChart() { const data=pnlSeries.map((value,i)=>({time:`${i+1}:00`,value})); return <Panel title="CUMULATIVE P&L" aside={<span className="text-sm font-semibold text-positive">+$68.40</span>}><div className="h-64 pt-4"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data}><defs><linearGradient id="pnl" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--positive)" stopOpacity={.3}/><stop offset="1" stopColor="var(--positive)" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="time" tick={{fill:"var(--muted-foreground)",fontSize:10}} axisLine={false}/><YAxis tick={{fill:"var(--muted-foreground)",fontSize:10}} axisLine={false}/><ChartTooltip contentStyle={{background:"var(--popover)",border:"1px solid var(--border)",borderRadius:6}}/><Area type="monotone" dataKey="value" stroke="var(--positive)" fill="url(#pnl)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></Panel>; }

export function SettingsSections() { const [state,setState]=useState<Record<string,boolean>>({"Compact density":true,"Signal sounds":false,"Desktop notifications":true,"Confirm paper orders":true,"Show low-liquidity tokens":false,"Auto-refresh demo feed":true,"Risk warnings":true,"Pause on daily limit":true}); const groups=["Appearance","Notifications","Trading preferences","Data preferences","Risk preferences","Bot preferences","About"]; return <div className="grid gap-4 md:grid-cols-2">{groups.map((g,gi)=><Panel title={g} key={g}>{g==="About"?<div className="space-y-3 text-sm text-muted-foreground"><p>HUNTER 2X Frontend Preview</p><p>Version 0.1 · Paper environment</p><DemoBadge/></div>:Object.keys(state).slice(gi,gi+2).map(k=><label className="toggle-row" key={k}><span>{k}</span><Switch checked={state[k]} onCheckedChange={v=>setState(s=>({...s,[k]:v}))}/></label>)}</Panel>)}</div>; }