/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAiAgentRouteImport } from './routes/_authenticated/ai-agent'
import { Route as AuthenticatedHunterMapRouteImport } from './routes/_authenticated/hunter-map'
import { Route as AuthenticatedPositionsRouteImport } from './routes/_authenticated/positions'
import { Route as AuthenticatedRiskRouteImport } from './routes/_authenticated/risk'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSmartMoneyRouteImport } from './routes/_authenticated/smart-money'
import { Route as AuthenticatedStrategiesRouteImport } from './routes/_authenticated/strategies'
import { Route as AuthenticatedTokenScannerRouteImport } from './routes/_authenticated/token-scanner'
import { Route as AuthenticatedTradeHistoryRouteImport } from './routes/_authenticated/trade-history'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiAgentRoute = AuthenticatedAiAgentRouteImport.update({
  id: '/ai-agent',
  path: '/ai-agent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHunterMapRoute = AuthenticatedHunterMapRouteImport.update({
  id: '/hunter-map',
  path: '/hunter-map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPositionsRoute = AuthenticatedPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRiskRoute = AuthenticatedRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSmartMoneyRoute = AuthenticatedSmartMoneyRouteImport.update({
  id: '/smart-money',
  path: '/smart-money',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStrategiesRoute = AuthenticatedStrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTokenScannerRoute =
  AuthenticatedTokenScannerRouteImport.update({
    id: '/token-scanner',
    path: '/token-scanner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTradeHistoryRoute =
  AuthenticatedTradeHistoryRouteImport.update({
    id: '/trade-history',
    path: '/trade-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/ai-agent': typeof AuthenticatedAiAgentRoute
  '/hunter-map': typeof AuthenticatedHunterMapRoute
  '/positions': typeof AuthenticatedPositionsRoute
  '/risk': typeof AuthenticatedRiskRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/smart-money': typeof AuthenticatedSmartMoneyRoute
  '/strategies': typeof AuthenticatedStrategiesRoute
  '/token-scanner': typeof AuthenticatedTokenScannerRoute
  '/trade-history': typeof AuthenticatedTradeHistoryRoute
  '/wallet': typeof AuthenticatedWalletRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/ai-agent': typeof AuthenticatedAiAgentRoute
  '/hunter-map': typeof AuthenticatedHunterMapRoute
  '/positions': typeof AuthenticatedPositionsRoute
  '/risk': typeof AuthenticatedRiskRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/smart-money': typeof AuthenticatedSmartMoneyRoute
  '/strategies': typeof AuthenticatedStrategiesRoute
  '/token-scanner': typeof AuthenticatedTokenScannerRoute
  '/trade-history': typeof AuthenticatedTradeHistoryRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ai-agent': typeof AuthenticatedAiAgentRoute
  '/_authenticated/hunter-map': typeof AuthenticatedHunterMapRoute
  '/_authenticated/positions': typeof AuthenticatedPositionsRoute
  '/_authenticated/risk': typeof AuthenticatedRiskRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/smart-money': typeof AuthenticatedSmartMoneyRoute
  '/_authenticated/strategies': typeof AuthenticatedStrategiesRoute
  '/_authenticated/token-scanner': typeof AuthenticatedTokenScannerRoute
  '/_authenticated/trade-history': typeof AuthenticatedTradeHistoryRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ai-agent'
    | '/hunter-map'
    | '/positions'
    | '/risk'
    | '/settings'
    | '/smart-money'
    | '/strategies'
    | '/token-scanner'
    | '/trade-history'
    | '/wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/ai-agent'
    | '/hunter-map'
    | '/positions'
    | '/risk'
    | '/settings'
    | '/smart-money'
    | '/strategies'
    | '/token-scanner'
    | '/trade-history'
    | '/wallet'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ai-agent'
    | '/_authenticated/hunter-map'
    | '/_authenticated/positions'
    | '/_authenticated/risk'
    | '/_authenticated/settings'
    | '/_authenticated/smart-money'
    | '/_authenticated/strategies'
    | '/_authenticated/token-scanner'
    | '/_authenticated/trade-history'
    | '/_authenticated/wallet'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-agent': {
      id: '/_authenticated/ai-agent'
      path: '/ai-agent'
      fullPath: '/ai-agent'
      preLoaderRoute: typeof AuthenticatedAiAgentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hunter-map': {
      id: '/_authenticated/hunter-map'
      path: '/hunter-map'
      fullPath: '/hunter-map'
      preLoaderRoute: typeof AuthenticatedHunterMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/positions': {
      id: '/_authenticated/positions'
      path: '/positions'
      fullPath: '/positions'
      preLoaderRoute: typeof AuthenticatedPositionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/risk': {
      id: '/_authenticated/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof AuthenticatedRiskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/smart-money': {
      id: '/_authenticated/smart-money'
      path: '/smart-money'
      fullPath: '/smart-money'
      preLoaderRoute: typeof AuthenticatedSmartMoneyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/strategies': {
      id: '/_authenticated/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof AuthenticatedStrategiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/token-scanner': {
      id: '/_authenticated/token-scanner'
      path: '/token-scanner'
      fullPath: '/token-scanner'
      preLoaderRoute: typeof AuthenticatedTokenScannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trade-history': {
      id: '/_authenticated/trade-history'
      path: '/trade-history'
      fullPath: '/trade-history'
      preLoaderRoute: typeof AuthenticatedTradeHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiAgentRoute: typeof AuthenticatedAiAgentRoute
  AuthenticatedHunterMapRoute: typeof AuthenticatedHunterMapRoute
  AuthenticatedPositionsRoute: typeof AuthenticatedPositionsRoute
  AuthenticatedRiskRoute: typeof AuthenticatedRiskRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSmartMoneyRoute: typeof AuthenticatedSmartMoneyRoute
  AuthenticatedStrategiesRoute: typeof AuthenticatedStrategiesRoute
  AuthenticatedTokenScannerRoute: typeof AuthenticatedTokenScannerRoute
  AuthenticatedTradeHistoryRoute: typeof AuthenticatedTradeHistoryRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiAgentRoute: AuthenticatedAiAgentRoute,
  AuthenticatedHunterMapRoute: AuthenticatedHunterMapRoute,
  AuthenticatedPositionsRoute: AuthenticatedPositionsRoute,
  AuthenticatedRiskRoute: AuthenticatedRiskRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSmartMoneyRoute: AuthenticatedSmartMoneyRoute,
  AuthenticatedStrategiesRoute: AuthenticatedStrategiesRoute,
  AuthenticatedTokenScannerRoute: AuthenticatedTokenScannerRoute,
  AuthenticatedTradeHistoryRoute: AuthenticatedTradeHistoryRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
